<?php
// Admin view route map used by the final fallback dispatcher.
$adminMap = [
 'admin' => 'dashboard/index','admin/dashboard' => 'dashboard/index','admin/setup-wizard'=>'setup-wizard/index','admin/commerce-complete'=>'commerce-complete/index','admin/menu-manager'=>'menu-manager/index',
 'admin/customers' => 'customers/index','admin/customers/add' => 'customers/add','admin/customers/view' => 'customers/view','admin/customers/service' => 'customers/service','admin/customers/groups' => 'customers/groups','admin/customer-sites'=>'customer-sites/index',
 'admin/orders' => 'orders/index','admin/orders/view' => 'orders/view','admin/orders/new' => 'orders/new','admin/orders/abandoned' => 'orders/abandoned',
 'admin/accounting' => 'accounting/index','admin/accounting/payment-fees'=>'accounting/payment-fees','admin/accounting/invoices' => 'accounting/invoices','admin/accounting/transactions' => 'accounting/transactions','admin/accounting/taxes' => 'accounting/taxes','admin/e-invoice'=>'e-invoice/index',
 'admin/domain-center' => 'domain-center/index','admin/domain-center/view' => 'domain-center/view','admin/domain-center/pricing' => 'domain-center/pricing','admin/domain-center/backorders' => 'domain-center/backorders','admin/domain-center/smart-pricing'=>'domain-center/smart-pricing','admin/domain-center/registrars' => 'domain-center/registrars','admin/domain-center/transfers' => 'domain-center/transfers','admin/domain-center/operations'=>'domain-center/operations',
 'admin/product-center' => 'product-center/index','admin/product-center/groups' => 'product-center/groups','admin/product-center/products' => 'product-center/products','admin/product-center/addons' => 'product-center/addons','admin/product-center/config-options' => 'product-center/config-options','admin/product-center/custom-fields' => 'product-center/custom-fields','admin/product-center/promotions' => 'product-center/promotions','admin/product-center/bundles' => 'product-center/bundles',
 'admin/hosting-server' => 'hosting-server/index','admin/hosting-server/servers' => 'hosting-server/servers','admin/hosting-server/health'=>'hosting-server/health','admin/hosting-server/accounts' => 'hosting-server/accounts','admin/hosting-server/whm' => 'hosting-server/whm','admin/hosting-server/directadmin'=>'hosting-server/directadmin','admin/hosting-server/plesk'=>'hosting-server/plesk','admin/hosting-server/vps'=>'hosting-server/vps',
 'admin/api-integrations' => 'api-integrations/index','admin/qa-scan-center'=>'qa-scan-center/index','admin/qa-visual-scan'=>'qa-visual-scan/index','admin/module-center'=>'module-center/index','admin/provider-center'=>'provider-center/index','admin/currency-center'=>'currency-center/index','admin/translation-center'=>'translation-center/index',
 'admin/notifications' => 'notifications/index','admin/notification-center'=>'notification-center/index','admin/search'=>'search/index',
 'admin/migration-bridge' => 'migration-bridge/index',
 'admin/product-updates'=>'product-updates/index','admin/license-injection'=>'license-injection/index','admin/ai-copilot'=>'ai-copilot/index','admin/operations-center'=>'operations-center/index',
 'admin/support' => 'support/index','admin/support/departments' => 'support/departments','admin/support/tickets' => 'support/tickets','admin/support/knowledgebase' => 'support/knowledgebase','admin/support/live-chat' => 'support/live-chat','admin/support/widget-settings'=>'support/widget-settings',
 'admin/automation' => 'automation/index','admin/reports' => 'reports/index',
 'admin/theme-center' => 'theme-center/themes','admin/theme-center/themes' => 'theme-center/themes','admin/theme-center/editor' => 'theme-center/editor','admin/theme-center/quick-actions'=>'theme-center/quick-actions','admin/site-heroes'=>'site-heroes/index',
 'admin/license-center'=>'license-center/index','admin/license-center/plans'=>'license-center/plans','admin/license-center/licenses'=>'license-center/licenses','admin/license-center/packages'=>'license-center/packages','admin/license-center/external'=>'license-center/external','admin/help-center'=>'help-center/index','admin/quotations'=>'quotations/index',
 'admin/builder-pro'=>'builder-pro/index','admin/site-builder' => 'site-builder/index','admin/site-builder/pages' => 'site-builder/pages','admin/site-builder/editor' => 'site-builder/editor','admin/site-builder/live-editor' => 'site-builder/live-editor','admin/site-builder/exports' => 'site-builder/exports','admin/site-builder/header' => 'site-builder/header','admin/site-builder/footer' => 'site-builder/footer','admin/site-builder/popups' => 'site-builder/popups','admin/site-builder/forms' => 'site-builder/forms',
 'admin/mobile-builder' => 'mobile-builder/index','admin/mobile-builder/editor' => 'mobile-builder/editor','admin/mobile-builder/ai' => 'mobile-builder/ai','admin/mobile-builder/exports' => 'mobile-builder/exports','admin/mobile-builder/build-queue' => 'mobile-builder/build-queue','admin/mobile-builder/build-center' => 'mobile-builder/build-center','admin/mobile-builder/build-log' => 'mobile-builder/build-log','admin/mobile-builder/build' => 'mobile-builder/build-center','admin/mobile-builder/menu' => 'mobile-builder/menu','admin/mobile-builder/bottom-bar' => 'mobile-builder/bottom-bar','admin/mobile-builder/cta' => 'mobile-builder/cta',
 'admin/build-center'=>'build-center/index','admin/build-center/environment'=>'build-center/environment','admin/build-center/sdk-tools'=>'build-center/sdk-tools','admin/build-center/queue'=>'build-center/queue','admin/build-center/logs'=>'build-center/logs','admin/build-center/repository'=>'build-center/repository','admin/build-center/settings'=>'build-center/settings',
 'admin/ai-center' => 'ai-center/index','admin/ai-center/site-analysis' => 'ai-center/site-analysis','admin/ai-center/seo' => 'ai-center/seo','admin/ai-center/automation' => 'ai-center/automation',
        'admin/seo-analyzer' => 'seo-analyzer',
 'admin/marketplace' => 'marketplace/index','admin/marketplace/categories'=>'marketplace/categories','admin/marketplace/offers'=>'marketplace/offers','admin/marketplace/escrow'=>'marketplace/escrow','admin/marketplace/auctions'=>'marketplace/auctions','admin/domain-intelligence'=>'domain-intelligence/index','admin/scan-report'=>'qa-scan-center/index','admin/production-test'=>'production-test/index','admin/security' => 'security/index','admin/cache-center'=>'cache-center/index','admin/backup-center'=>'backup-center/index','admin/update-center'=>'update-center/index','admin/logs' => 'logs/index','admin/settings' => 'settings/index','admin/health-center' => 'health-center/index','admin/affiliate' => 'affiliate/index','admin/references'=>'references/index','admin/blog'=>'blog/index','admin/blog/post'=>'blog/post','admin/kanban'=>'kanban/index','admin/2fa'=>'security/2fa','admin/api-gateway'=>'api-gateway/index','admin/email-templates' => 'email-templates/index','admin/live-chat' => 'live-chat/index','admin/site-builder/ai-design' => 'site-builder/ai-design','admin/mobile-builder/ai-app' => 'mobile-builder/ai-app','api/ai-generate-site' => 'api/ai-generate-site','api/ai-generate-app' => 'api/ai-generate-app'
];
