<?php
// Help guide CMS routes and helpers.
if (!function_exists('ao_help_slug')) {
    function ao_help_slug($text){
        $text=mb_strtolower(trim((string)$text),'UTF-8');
        $map=['ı'=>'i','ğ'=>'g','ü'=>'u','ş'=>'s','ö'=>'o','ç'=>'c'];
        $text=strtr($text,$map);
        $text=preg_replace('/[^a-z0-9]+/','-',$text);
        return trim($text,'-') ?: 'yardim';
    }
    function ao_help_table_exists($table){ try{ db()->query('SELECT 1 FROM `'.$table.'` LIMIT 1'); return true; }catch(Throwable $e){ return false; } }
    function ao_help_columns($table){ try{ return array_map(fn($r)=>$r['Field']??$r[0], db()->query('SHOW COLUMNS FROM `'.$table.'`')->fetchAll()); }catch(Throwable $e){ return []; } }
    function ao_help_install(){
        try{
            db()->exec("CREATE TABLE IF NOT EXISTS help_categories (id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(190) NOT NULL, slug VARCHAR(190) NOT NULL, icon VARCHAR(30) DEFAULT '❔', description TEXT NULL, sort_order INT DEFAULT 0, is_active TINYINT(1) DEFAULT 1, created_at DATETIME NULL, updated_at DATETIME NULL, UNIQUE KEY help_categories_slug_unique (slug)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
            db()->exec("CREATE TABLE IF NOT EXISTS help_articles (id INT AUTO_INCREMENT PRIMARY KEY, category_id INT NULL, title VARCHAR(190) NOT NULL, slug VARCHAR(190) NOT NULL, summary TEXT NULL, content MEDIUMTEXT NULL, related_label VARCHAR(190) NULL, related_route VARCHAR(190) NULL, tags VARCHAR(255) NULL, status VARCHAR(30) DEFAULT 'published', sort_order INT DEFAULT 0, views INT DEFAULT 0, created_at DATETIME NULL, updated_at DATETIME NULL, UNIQUE KEY help_articles_slug_unique (slug), KEY help_articles_category_idx (category_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
            foreach([
                'category_id'=>'INT NULL','slug'=>'VARCHAR(190) NULL','summary'=>'TEXT NULL','content'=>'MEDIUMTEXT NULL','related_label'=>'VARCHAR(190) NULL','related_route'=>'VARCHAR(190) NULL','tags'=>'VARCHAR(255) NULL','status'=>"VARCHAR(30) DEFAULT 'published'",'sort_order'=>'INT DEFAULT 0','views'=>'INT DEFAULT 0','updated_at'=>'DATETIME NULL'
            ] as $col=>$def){ try{ db()->exec("ALTER TABLE help_articles ADD COLUMN IF NOT EXISTS {$col} {$def}"); }catch(Throwable $e){ error_log('[ao] '.$e->getMessage().' @ '.$e->getFile().':'.$e->getLine()); } }
        }catch(Throwable $e){ return; }
        try{
            db()->exec("INSERT IGNORE INTO help_categories (title,slug,icon,description,sort_order,is_active,created_at,updated_at) VALUES ('Lisans Merkezi','lisans-merkezi','🔐','Ahost One, web tasarım ve Android ürünleri için offline-first lisans yönetimi.',115,1,NOW(),NOW())");
            $licCat=(int)db()->query("SELECT id FROM help_categories WHERE slug='lisans-merkezi' LIMIT 1")->fetchColumn();
            if($licCat>0){
                $licContent='License Center Pro; site içi satış, CodeCanyon ve manuel lisansları aynı yerden yönetir. Site içi satışta purchase code istenmez. CodeCanyon/Envato satışında purchase code zorunludur. Ahost One ve web tasarım ürünlerinde müşteri domaini girilir; install.php lisans kodunu doğrular ve domain eşleşirse kurulum devam eder. Android uygulamalarda package name girilir ve lisans kodu uygulama dosyalarından birine eklenir; package name eşleşmezse uygulama çalışmamalıdır. Android lisansı ömür boyudur. Ahost One ve web tasarım lisansları aylık, yıllık veya ömür boyu olabilir. Sistem offline-first tasarlanır: Ahost One kapanırsa ömür boyu lisanslar çalışmaya devam eder; aylık/yıllık lisanslar lisans dosyasındaki bitiş tarihine kadar çalışır, tarih dolunca kapanır. Lisans düz metin yerine imzalı payload, license.json, license.sig ve public key ile doğrulanır. Private key sadece ana lisans sisteminde kalır.';
                db()->prepare("INSERT INTO help_articles (category_id,title,slug,summary,content,related_label,related_route,tags,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?, 'published',NOW(),NOW()) ON DUPLICATE KEY UPDATE summary=VALUES(summary),content=VALUES(content),related_label=VALUES(related_label),related_route=VALUES(related_route),tags=VALUES(tags),updated_at=NOW()")->execute([$licCat,'Ahost One lisans sistemi nasıl çalışır?','ahost-one-lisans-sistemi-nasil-calisir','Domain, package name, purchase code ve offline-first lisans mantığı.',$licContent,'License Center’a Git','admin/license-center','lisans,codecanyon,purchase code,domain,package name,android,offline']);
            }
            $count=(int)db()->query('SELECT COUNT(*) FROM help_categories')->fetchColumn();
            if($count>1) return;
            $cats=[
                ['Başlangıç','baslangic','🚀','İlk giriş, panel mantığı ve hızlı kurulum.'],
                ['Genel Ayarlar','genel-ayarlar','⚙','Site adı, logo, SMTP, para birimi ve temel ayarlar.'],
                ['Footer Düzenleme','footer-duzenleme','🧭','Footer linkleri, sosyal ikonlar, açıklama ve telif alanı.'],
                ['Domain Yönetimi','domain-yonetimi','🌐','Registrar, transfer, EPP, DNS, nameserver ve whois işlemleri.'],
                ['Hosting & Sunucu','hosting-sunucu','🖥','WHM/cPanel, Plesk, DirectAdmin, VPS ve hesap yönetimi.'],
                ['Fatura & KDV','fatura-kdv','₺','Faturalar, vergiler, KDV, tahsilat ve ödeme kayıtları.'],
                ['Destek Talepleri','destek-talepleri','🎧','Ticket listesi, otomatik yanıtlar, departmanlar ve widget.'],
                ['Builder','builder','🎨','Sayfa oluşturma, tema önizleme, mobile builder ve blok yapısı.'],
                ['Yapay Zeka','yapay-zeka','🤖','Ücretsiz AI sağlayıcıları, bilgi bankası ve analiz yorumlama.'],
                ['SEO / Site / Domain Analizi','seo-site-domain-analizi','🔎','Gerçek tarama, SEO raporu, whois, domain değerlendirme ve QA raporları.'],
                ['Migration & Lisanslama','migration-lisanslama','🔁','WHMCS, WiseCP, Blesta aktarımı ve zip lisanslama işlemleri.'],
                ['Güvenlik & 2FA','guvenlik-2fa','🛡','2FA, yetkiler, audit log, yedekleme ve güvenlik kontrolleri.'],
            ];
            $st=db()->prepare('INSERT INTO help_categories (title,slug,icon,description,sort_order,is_active,created_at,updated_at) VALUES (?,?,?,?,?,1,NOW(),NOW())');
            foreach($cats as $i=>$c) $st->execute([$c[0],$c[1],$c[2],$c[3],($i+1)*10]);
            $catMap=[]; foreach(db()->query('SELECT id,slug FROM help_categories')->fetchAll() as $r) $catMap[$r['slug']]=$r['id'];
            $articles=[
                ['footer-duzenleme','Footer nasıl düzenlenir?','Footer logo, açıklama, hızlı linkler, sosyal medya ikonları ve telif yazısını düzenlemek için ilgili footer ayar sayfasına gidin. Değişiklikten sonra ön yüzü kontrol edin.','Footer alanında marka açıklaması, sosyal ikonlar, hızlı linkler, iletişim bilgileri ve telif metni bulunur. Önce mevcut bilgileri yedekleyin, ardından footer ayar ekranında gerekli alanları doldurun. Linkleri eklerken tam URL veya sistem içi rota kullanın. Sosyal ikonlarda sadece aktif hesapları gösterin. Kaydettikten sonra site ön yüzünde masaüstü ve mobil görünümü kontrol edin.','Footer Ayarlarına Git','admin/settings?tab=footer','footer,alt alan,sosyal ikon'],
                ['genel-ayarlar','Genel ayarlar nasıl yapılır?','Site adı, logo, e-posta, para birimi ve temel çalışma ayarlarını tek ekrandan yönetin.','Genel ayarlar canlı sistemin temelidir. Site adı, logo, varsayılan dil, para birimi, SMTP, destek e-postası ve bakım modu gibi ayarları tamamlayın. Boş bırakılan alanlar bazı modüllerde eksik bilgi gösterebilir.','Genel Ayarlara Git','admin/settings','genel ayarlar,site adı,logo'],
                ['domain-yonetimi','Domain transferi ve EPP kodu','Domain transferinde alan adı, EPP kodu, müşteri e-postası ve registrar seçimi gerekir.','Yeni transfer başlatırken domain adını doğru yazın, müşteriden alınan EPP kodunu ekleyin ve transfer edilecek registrar sağlayıcısını seçin. Transfer kilidi açık ise önce kilidi kapatmanız gerekebilir.','Domain Transferlerine Git','admin/domain-center/transfers?new=1','domain transfer,epp,registrar'],
                ['domain-yonetimi','Registrar ayarları nasıl eklenir?','DomainNameAPI, OpenSRS, ResellerClub, NameSilo gibi sağlayıcıların API bilgileri bu alandan tanımlanır.','Registrar ayarında test/canlı mod ayrımına dikkat edin. Önce sandbox veya test bilgisiyle bağlantı testi yapın. Başarılı olursa canlı anahtarları girip varsayılan registrar seçin.','Registrar Ayarlarına Git','admin/domain-center/registrars','registrar,api key,domainnameapi'],
                ['fatura-kdv','KDV ve vergi nasıl düzenlenir?','Vergiler ekranından KDV oranı, vergi adı ve uygulanacak fatura kuralları düzenlenir.','Faturalarda KDV görünmesi için vergi oranı aktif olmalı ve fatura hesaplama kayıtlarında kullanılmalıdır. Düzenleme sonrası örnek bir fatura oluşturup ara toplam, vergi ve genel toplamı kontrol edin.','Vergi Ayarlarına Git','admin/accounting/taxes','kdv,vergi,fatura'],
                ['destek-talepleri','Destek talebi nasıl yönetilir?','Ticket listesinde talebi açın, müşterinin mesajını okuyun, departman ve durum bilgilerini güncelleyin.','Destek talebinde öncelik, atanan personel, hazır cevap ve otomatik yanıt ayarlarını kullanın. Domain veya hosting kaynaklı taleplerde önce ilgili servisi kontrol edin.','Ticketlara Git','admin/support/tickets','ticket,destek,otomatik yanıt'],
                ['builder','Normal sayfa nasıl oluşturulur?','Hakkımızda, iletişim ve yasal sayfalar için normal içerik sayfası oluşturun; builder sadece tasarım gereken sayfalarda kullanılır.','Sayfa oluştururken başlık, slug, içerik, SEO başlığı ve görünürlük durumunu seçin. Yasal sayfalarda hazır şablon kullanabilir, normal sayfalarda WYSIWYG içerik ekleyebilirsiniz.','Sayfalara Git','admin/pages','sayfa,hakkımızda,içerik'],
                ['builder','Tema önizleme nasıl kullanılır?','Aktif temaya dokunmadan diğer temaları önizleyebilir ve içerik bloklarını kontrol edebilirsiniz.','Tema önizleme sisteminde renk, blok sırası, hero alanı, ürün kartları ve footer düzeni ayrı ayrı kontrol edilir. Önizleme canlı temayı değiştirmez.','Temalara Git','admin/theme-center/themes','tema,önizleme,builder'],
                ['yapay-zeka','Yapay zeka ayarları nasıl yapılır?','Gemini, Groq, OpenRouter veya Ollama sağlayıcılarını ekleyip test bağlantısı yapın.','Ücretsiz sağlayıcı kullanmak için ilgili servisten API key alın ve AI Center ekranına girin. API yoksa yerel bilgi motoru bilgi bankasında arama yapar ve admin onaylı taslak oluşturur.','AI Center’a Git','admin/ai-center','ai,gemini,groq,openrouter'],
                ['seo-site-domain-analizi','SEO ve site analizi nasıl çalışır?','Sistem gerçek verileri toplar; AI sadece bulguları sadeleştirip öneriye dönüştürür.','SEO analizinde title, description, canonical, robots, sitemap, başlık hiyerarşisi, linkler, SSL ve güvenlik başlıkları kontrol edilir. Raporu çalıştırdıktan sonra yüksek öncelikli maddelerden başlayın.','QA Scan Center’a Git','admin/qa-scan-center','seo,site analizi,qa scan'],
                ['migration-lisanslama','Migration aktarımı nasıl yapılır?','WHMCS, WiseCP, Blesta gibi kaynaklardan müşteri, ürün, domain, fatura ve ticket kayıtları seçilerek aktarılır.','Önce dry-run yapın. Kayıtlar tablo halinde listelenir. Sadece işaretlenen kayıtlar aktarılır. Bridge map aynı kaydın tekrar oluşmasını engeller.','Migration’a Git','admin/migration-bridge','migration,whmcs,wisecp,blesta'],
                ['guvenlik-2fa','2FA güvenlik nasıl açılır?','Admin hesabı için iki aşamalı doğrulama aktif edilerek panel güvenliği artırılır.','2FA ekranından doğrulama yöntemini seçin, kodu taratın ve yedek kodları güvenli yerde saklayın. Yetki gruplarında kritik menüleri sadece gerekli personele açın.','2FA Ayarlarına Git','admin/security/2fa','2fa,güvenlik,yetki'],
            ];
            $st=db()->prepare('INSERT INTO help_articles (category_id,title,slug,summary,content,related_label,related_route,tags,status,sort_order,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,NOW(),NOW())');
            foreach($articles as $i=>$a){ $slug=ao_help_slug($a[1]); $st->execute([$catMap[$a[0]]??null,$a[1],$slug,$a[2],$a[3],$a[4],$a[5],$a[6],'published',($i+1)*10]); }
        }catch(Throwable $e){ error_log('[ao] '.$e->getMessage().' @ '.$e->getFile().':'.$e->getLine()); }
    }
    function ao_help_categories(){ ao_help_install(); try{return db()->query('SELECT * FROM help_categories ORDER BY sort_order,id')->fetchAll() ?: [];}catch(Throwable $e){return [];} }
    function ao_help_articles($where='1=1',$params=[]){ ao_help_install(); try{$st=db()->prepare('SELECT a.*,c.title category_title,c.icon category_icon FROM help_articles a LEFT JOIN help_categories c ON c.id=a.category_id WHERE '.$where.' ORDER BY a.sort_order,a.id DESC'); $st->execute($params); return $st->fetchAll()?:[];}catch(Throwable $e){return [];} }
    function ao_help_article($id){ ao_help_install(); try{$st=db()->prepare('SELECT a.*,c.title category_title,c.icon category_icon FROM help_articles a LEFT JOIN help_categories c ON c.id=a.category_id WHERE a.id=? LIMIT 1'); $st->execute([(int)$id]); return $st->fetch() ?: null;}catch(Throwable $e){return null;} }
    function ao_help_cat_options($selected=0){ $html=''; foreach(ao_help_categories() as $c){ $sel=((int)$c['id']==(int)$selected)?' selected':''; $html.='<option value="'.(int)$c['id'].'"'.$sel.'>'.e(($c['icon']?:'❔').' '.$c['title']).'</option>'; } return $html; }
}

if (in_array($route,['admin/help-guide','admin/help-center'],true)) { require_admin(); ao_help_install();
    $q=trim((string)($_GET['q']??''));
    $articles=$q!==''?ao_help_articles('(a.title LIKE ? OR a.summary LIKE ? OR a.content LIKE ? OR a.tags LIKE ?)',array_fill(0,4,'%'.$q.'%')):ao_help_articles('a.status<>?',['deleted']);
    $minutes=[5,15,10,5,10,15,8,7,6,10];
    $topicCards=''; $manageRows='';
    foreach(array_slice($articles,0,60) as $i=>$a){
        $summary=trim((string)($a['summary']??'')); if($summary==='') $summary=trim(mb_substr(strip_tags((string)($a['content']??'')),0,120,'UTF-8'));
        $minute=$minutes[$i % count($minutes)];
        $topicCards.='<a class="ao-help-topic-card" href="'.url('admin/help-guide/article?id='.(int)$a['id']).'"><span class="ao-help-topic-no">'.($i+1).'</span><span class="ao-help-topic-copy"><strong>'.e($a['title']).'</strong><small>'.e($summary).'</small><em>'.$minute.' dk</em></span></a>';
        $delete='<form method="post" action="'.url('admin/help-guide/articles/delete').'" onsubmit="return confirm(\'Yardım konusu silinsin mi?\')">'.csrf_field().'<input type="hidden" name="id" value="'.(int)$a['id'].'"><button class="ao-mini-btn soft">Sil</button></form>';
        $manageRows.='<div class="ao-help-manage-row"><div><b>'.e($a['title']).'</b><small>'.e($a['category_title']??'Kategorisiz').'</small></div><div class="ao-help-manage-actions"><a class="ao-mini-btn soft" href="'.url('admin/help-guide/articles/edit?id='.(int)$a['id']).'">Düzenle</a>'.$delete.'</div></div>';
    }
    if($topicCards==='') $topicCards='<div class="ao-card">Henüz yardım konusu yok. Sağ taraftan yeni yardım ekleyebilirsiniz.</div>';
    if($manageRows==='') $manageRows='<p class="ao-help-empty">Henüz yönetilecek yardım yok.</p>';
    $search='<form class="ao-help-compact-search" method="get" action="'.url('admin/help-guide').'"><input name="q" value="'.e($q).'" placeholder="Yardım konusu ara"><button class="ao-mini-btn">Ara</button></form>';
    $side='<aside class="ao-help-manage-panel"><div class="ao-help-manage-head"><h3>Yönetim</h3><a class="ao-btn" href="'.url('admin/help-guide/articles/create').'">+ Yeni Yardım Ekle</a></div>'.$search.'<a class="ao-mini-btn soft" href="'.url('admin/help-guide/categories').'">Kategoriler</a><div class="ao-help-manage-list">'.$manageRows.'</div></aside>';
    $html='<div class="ao-page-head"><div><h2>Yardım Kılavuzu</h2><p>Yardım konuları kartlar halinde listelenir. Karta tıklayınca yapılacaklar ekranı açılır.</p></div></div><div class="ao-help"><section class="ao-help-main-panel"><div class="ao-help-topic-grid">'.$topicCards.'</div></section>'.$side.'</div>';
    ao_admin_fallback_shell('Yardım Kılavuzu',$html);
}

if ($route==='admin/help-guide/categories') { require_admin(); ao_help_install();
    $edit=null; if(isset($_GET['edit'])){ foreach(ao_help_categories() as $c) if((int)$c['id']==(int)$_GET['edit']) $edit=$c; }
    $rows=''; foreach(ao_help_categories() as $c){ $rows.='<tr><td>'.e($c['icon']).' <strong>'.e($c['title']).'</strong><br><small>'.e($c['description']??'').'</small></td><td>'.e($c['slug']).'</td><td>'.(int)$c['sort_order'].'</td><td>'.((int)$c['is_active']?'Aktif':'Pasif').'</td><td><a class="ao-mini-btn" href="'.url('admin/help-guide/categories?edit='.(int)$c['id']).'">Düzenle</a> <form style="display:inline" method="post" action="'.url('admin/help-guide/categories/delete').'">'.csrf_field().'<input type="hidden" name="id" value="'.(int)$c['id'].'"><button class="ao-mini-btn soft" onclick="return confirm(\'Kategori silinsin mi?\')">Sil</button></form></td></tr>'; }
    $form='<form method="post" action="'.url('admin/help-guide/categories/save').'">'.csrf_field().'<input type="hidden" name="id" value="'.(int)($edit['id']??0).'"><div class="ao-grid two"><label>Başlık<input name="title" value="'.e($edit['title']??'').'" required></label><label>İkon<input name="icon" value="'.e($edit['icon']??'❔').'" maxlength="30"></label><label>Sıra<input type="number" name="sort_order" value="'.e($edit['sort_order']??'0').'"></label><label>Durum<select name="is_active"><option value="1">Aktif</option><option value="0" '.(((int)($edit['is_active']??1)===0)?'selected':'').'>Pasif</option></select></label></div><label>Açıklama<textarea name="description">'.e($edit['description']??'').'</textarea></label><button class="ao-btn">Kaydet</button></form>';
    ao_admin_fallback_shell('Yardım Kategorileri','<div class="ao-page-head"><div><h2>Yardım Kategorileri</h2><p>Yardım kılavuzundaki ana başlıkları buradan yönet.</p></div><a class="ao-btn soft" href="'.url('admin/help-guide').'">Yardım Kılavuzu</a></div><div class="ao-grid two"><div class="ao-card"><h3>'.($edit?'Kategori Düzenle':'Yeni Kategori').'</h3>'.$form.'</div><div class="ao-card"><h3>Kategori Listesi</h3><div class="ao-table-wrap"><table class="ao-table"><tr><th>Kategori</th><th>Slug</th><th>Sıra</th><th>Durum</th><th>İşlem</th></tr>'.$rows.'</table></div></div></div>');
}
if ($_SERVER['REQUEST_METHOD']==='POST' && $route==='admin/help-guide/categories/save') { require_admin(); verify_csrf(); ao_help_install(); $id=(int)($_POST['id']??0); $title=trim((string)($_POST['title']??'')); $slug=ao_help_slug($title); $data=[$title,$slug,trim((string)($_POST['icon']??'❔')),trim((string)($_POST['description']??'')),(int)($_POST['sort_order']??0),(int)($_POST['is_active']??1)]; try{ if($id>0){ db()->prepare('UPDATE help_categories SET title=?,slug=?,icon=?,description=?,sort_order=?,is_active=?,updated_at=NOW() WHERE id=?')->execute([...$data,$id]); } else { db()->prepare('INSERT INTO help_categories (title,slug,icon,description,sort_order,is_active,created_at,updated_at) VALUES (?,?,?,?,?,?,NOW(),NOW())')->execute($data); } flash('success','Yardım kategorisi kaydedildi.'); }catch(Throwable $e){ flash('error','Kategori kaydedilemedi: '.$e->getMessage()); } redirect_to('admin/help-guide/categories'); }
if ($_SERVER['REQUEST_METHOD']==='POST' && $route==='admin/help-guide/categories/delete') { require_admin(); verify_csrf(); ao_help_install(); try{ db()->prepare('DELETE FROM help_categories WHERE id=?')->execute([(int)($_POST['id']??0)]); flash('success','Kategori silindi.'); }catch(Throwable $e){ flash('error','Kategori silinemedi.'); } redirect_to('admin/help-guide/categories'); }

if (in_array($route,['admin/help-guide/articles','admin/help-guide/articles/create','admin/help-guide/articles/edit'],true)) { require_admin(); ao_help_install();
    $edit=null; if($route==='admin/help-guide/articles/edit') $edit=ao_help_article((int)($_GET['id']??0));
    if($route==='admin/help-guide/articles/create' || $edit){
        $form='<form method="post" action="'.url('admin/help-guide/articles/save').'">'.csrf_field().'<input type="hidden" name="id" value="'.(int)($edit['id']??0).'"><div class="ao-grid two"><label>Başlık<input name="title" value="'.e($edit['title']??'').'" required></label><label>Kategori<select name="category_id">'.ao_help_cat_options((int)($edit['category_id']??0)).'</select></label><label>İlgili Buton Yazısı<input name="related_label" value="'.e($edit['related_label']??'İlgili Sayfaya Git').'"></label><label>İlgili Route / Link<input name="related_route" value="'.e($edit['related_route']??'').'" placeholder="admin/settings?tab=footer"></label><label>Etiketler<input name="tags" value="'.e($edit['tags']??'').'" placeholder="footer, kdv, domain"></label><label>Durum<select name="status"><option value="published">Yayında</option><option value="draft" '.((($edit['status']??'')==='draft')?'selected':'').'>Taslak</option><option value="hidden" '.((($edit['status']??'')==='hidden')?'selected':'').'>Gizli</option></select></label></div><label>Kısa Açıklama<textarea name="summary">'.e($edit['summary']??'').'</textarea></label><label>Detaylı İçerik<textarea name="content" rows="12" placeholder="Adım adım anlatım, dikkat edilecekler, örnek kullanım...">'.e($edit['content']??'').'</textarea></label><button class="ao-btn">Makale Kaydet</button></form>';
        ao_admin_fallback_shell($edit?'Yardım Makalesi Düzenle':'Yeni Yardım Makalesi','<div class="ao-page-head"><div><h2>'.($edit?'Yardım Makalesi Düzenle':'Yeni Yardım Makalesi').'</h2><p>Makale içeriği, kategori, etiket ve ilgili sayfaya git butonu buradan yönetilir.</p></div><a class="ao-btn soft" href="'.url('admin/help-guide').'">Geri</a></div><div class="ao-card">'.$form.'</div>');
    }
    $where='a.status<>?'; $params=['deleted']; if(isset($_GET['category_id'])){ $where.=' AND a.category_id=?'; $params[]=(int)$_GET['category_id']; }
    $cards='<a class="ao-card ao-help-add-card" href="'.url('admin/help-guide/articles/create').'"><h3>+ Yeni Ekle</h3><p>Yeni yardım konusu oluştur, açıklamasını ve ilgili ayar bağlantısını belirle.</p><span class="ao-mini-btn">Yeni Makale</span></a>';
    foreach(ao_help_articles($where,$params) as $a){
        $rr=trim((string)($a['related_route']??''));
        $href=$rr!==''?(preg_match('#^https?://#',$rr)?$rr:url($rr)):'';
        $go=$href!==''?'<a class="ao-mini-btn" href="'.e($href).'">'.e($a['related_label']?:'İlgili Ayara Git').'</a>':'';
        $delete='<form method="post" action="'.url('admin/help-guide/articles/delete').'" onsubmit="return confirm(&quot;Makale silinsin mi?&quot;)">'.csrf_field().'<input type="hidden" name="id" value="'.(int)$a['id'].'"><button class="ao-mini-btn soft">Sil</button></form>';
        $cards.='<article class="ao-card ao-help-card"><div class="ao-help-card-head"><small>'.e(($a['category_icon']??'').' '.($a['category_title']??'-')).'</small><details class="ao-help-options"><summary>Seçenekler</summary><div><a class="ao-mini-btn soft" href="'.url('admin/help-guide/articles/edit?id='.(int)$a['id']).'">Düzenle</a>'.$delete.'</div></details></div><a href="'.url('admin/help-guide/article?id='.(int)$a['id']).'" style="display:block;text-decoration:none;color:inherit"><h3>'.e($a['title']).'</h3><p>'.e($a['summary']??'').'</p></a><div class="ao-actions">'.$go.'</div></article>';
    }
    ao_admin_fallback_shell('Yardım Makaleleri','<div class="ao-page-head"><div><h2>Yardım Makaleleri</h2><p>Karta tıklayınca yardım içeriği doğrudan açılır. Düzenle ve sil işlemleri Seçenekler menüsündedir.</p></div><a class="ao-btn" href="'.url('admin/help-guide/articles/create').'">+ Yeni Makale</a></div><div class="ao-help-grid">'.$cards.'</div>');
}
if ($_SERVER['REQUEST_METHOD']==='POST' && $route==='admin/help-guide/articles/save') { require_admin(); verify_csrf(); ao_help_install(); $id=(int)($_POST['id']??0); $title=trim((string)($_POST['title']??'')); $slug=ao_help_slug($title); $data=[(int)($_POST['category_id']??0),$title,$slug,trim((string)($_POST['summary']??'')),trim((string)($_POST['content']??'')),trim((string)($_POST['related_label']??'')),trim((string)($_POST['related_route']??'')),trim((string)($_POST['tags']??'')),trim((string)($_POST['status']??'published'))]; try{ if($id>0){ db()->prepare('UPDATE help_articles SET category_id=?,title=?,slug=?,summary=?,content=?,related_label=?,related_route=?,tags=?,status=?,updated_at=NOW() WHERE id=?')->execute([...$data,$id]); } else { db()->prepare('INSERT INTO help_articles (category_id,title,slug,summary,content,related_label,related_route,tags,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,NOW(),NOW())')->execute($data); } flash('success','Yardım makalesi kaydedildi.'); }catch(Throwable $e){ flash('error','Makale kaydedilemedi: '.$e->getMessage()); } redirect_to('admin/help-guide'); }
if ($_SERVER['REQUEST_METHOD']==='POST' && $route==='admin/help-guide/articles/delete') { require_admin(); verify_csrf(); ao_help_install(); try{ db()->prepare('DELETE FROM help_articles WHERE id=?')->execute([(int)($_POST['id']??0)]); flash('success','Makale silindi.'); }catch(Throwable $e){ flash('error','Makale silinemedi.'); } redirect_to('admin/help-guide'); }
if ($route==='admin/help-guide/article') { require_admin(); ao_help_install(); $a=ao_help_article((int)($_GET['id']??0)); if(!$a) ao_admin_fallback_shell('Yardım Makalesi','<div class="ao-card">Makale bulunamadı.</div>'); try{ db()->prepare('UPDATE help_articles SET views=views+1 WHERE id=?')->execute([(int)$a['id']]); }catch(Throwable $e){ error_log('[ao] '.$e->getMessage().' @ '.$e->getFile().':'.$e->getLine()); }
    $rr=trim((string)($a['related_route']??'')); $go=''; if($rr!==''){ $href=preg_match('#^https?://#',$rr)?$rr:url($rr); $go='<a class="ao-btn" href="'.e($href).'">'.e($a['related_label']?:'İlgili Ayar Alanına Git').'</a>'; }
    $raw=trim((string)($a['content']??'')); $lines=array_values(array_filter(array_map('trim',preg_split('/\R+/', $raw))));
    $steps=''; $note=''; foreach($lines as $ln){ if(mb_strlen($ln,'UTF-8')<180 && preg_match('/^(not|uyarı|ipucu|bilgilendirme)[:：]/iu',$ln)){ $note=preg_replace('/^(not|uyarı|ipucu|bilgilendirme)[:：]\s*/iu','',$ln); continue; } $steps.='<li>'.e(preg_replace('/^\d+[\.)]\s*/','',$ln)).'</li>'; }
    if($steps==='') $steps='<li>'.e($a['summary'] ?: 'Bu yardım konusu için ilgili ayar sayfasına gidin ve alanları kontrol edin.').'</li>';
    if($note==='') $note='Değişiklikten sonra sayfayı yenileyin ve gerekirse önbelleği temizleyin.';
    $stepNo=max(1,(int)ceil(((int)($a['sort_order']??10))/10));
    $cleanTitle=preg_replace('/\s+nasıl yapılır\??$/iu','',(string)$a['title']);
    $stepTitle='Adım '.$stepNo.': '.$cleanTitle;
    $next=''; try{ $n=db()->prepare("SELECT id,title FROM help_articles WHERE status='published' AND id<>? AND (category_id=? OR ?=0) ORDER BY sort_order ASC,id ASC LIMIT 1"); $n->execute([(int)$a['id'],(int)($a['category_id']??0),(int)($a['category_id']??0)]); $nx=$n->fetch(); if($nx){ $next='<a class="ao-btn" href="'.url('admin/help-guide/article?id='.(int)$nx['id']).'">Sonraki: '.e($nx['title']).'</a>'; } }catch(Throwable $e){ error_log('[ao] '.$e->getMessage().' @ '.$e->getFile().':'.$e->getLine()); }
    if($next==='') $next='<a class="ao-btn" href="'.url('admin/help-guide').'">Sonraki: Yardım Kılavuzu</a>';
    $delete='<form method="post" action="'.url('admin/help-guide/articles/delete').'" onsubmit="return confirm(\'Yardım konusu silinsin mi?\')">'.csrf_field().'<input type="hidden" name="id" value="'.(int)$a['id'].'"><button class="ao-mini-btn soft">Sil</button></form>';
    $side='<aside class="ao-help-manage-panel"><div class="ao-help-manage-head"><h3>Yönetim</h3><a class="ao-btn" href="'.url('admin/help-guide/articles/create').'">+ Yeni Yardım Ekle</a></div><div class="ao-help-current-topic"><b>'.e($a['title']).'</b><small>'.e($a['category_title']??'Kategorisiz').'</small><div class="ao-help-manage-actions"><a class="ao-mini-btn soft" href="'.url('admin/help-guide/articles/edit?id='.(int)$a['id']).'">Düzenle</a>'.$delete.'</div></div></aside>';
    $html='<div class="ao-help ao-help-detail"><section class="ao-help-detail-card"><h1>Yapılacaklar</h1><p class="ao-help-detail-summary">'.e($a['summary']??$stepTitle).'</p><ol class="ao-help-todo-list">'.$steps.'</ol><div class="ao-help-note">'.e($note).'</div>'.($go?'<div class="ao-help-related">'.$go.'</div>':'').'<div class="ao-help-detail-actions"><a class="ao-btn soft" href="'.url('admin/help-guide').'">Ana Sayfa</a>'.$next.'</div></section>'.$side.'</div>';
    ao_admin_fallback_shell($a['title'],$html);
}

