<?php
// v22.3.8 Stability + SaaS completion helpers
function ao_v238_table_cols($table){ try{$rows=db()->query("SHOW COLUMNS FROM `$table`")->fetchAll(); $out=[]; foreach($rows as $r){$out[$r['Field']]=true;} return $out;}catch(Throwable $e){return [];} }
function ao_v238_ensure_schema(){ static $done=false; if($done) return; $done=true;
    try{ db()->exec("CREATE TABLE IF NOT EXISTS product_custom_fields (id INT AUTO_INCREMENT PRIMARY KEY, group_id INT DEFAULT 0, product_id INT DEFAULT 0, field_key VARCHAR(120) NOT NULL, label VARCHAR(190) NOT NULL, field_type VARCHAR(40) DEFAULT 'text', options TEXT NULL, is_required TINYINT(1) DEFAULT 0, is_active TINYINT(1) DEFAULT 1, sort_order INT DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uniq_field_key(field_key)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"); }catch(Throwable $e){ error_log('[ao] '.$e->getMessage().' @ '.$e->getFile().':'.$e->getLine()); }
    try{ db()->exec("CREATE TABLE IF NOT EXISTS product_promotions (id INT AUTO_INCREMENT PRIMARY KEY, code VARCHAR(80) NOT NULL, title VARCHAR(190) NULL, discount_type VARCHAR(20) DEFAULT 'percent', discount_value DECIMAL(14,2) DEFAULT 0, min_total DECIMAL(14,2) DEFAULT 0, usage_limit INT DEFAULT 0, used_count INT DEFAULT 0, starts_at DATE NULL, ends_at DATE NULL, is_active TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uniq_promo_code(code)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"); }catch(Throwable $e){ error_log('[ao] '.$e->getMessage().' @ '.$e->getFile().':'.$e->getLine()); }
    try{ db()->exec("CREATE TABLE IF NOT EXISTS package_builders (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(190) NOT NULL, base_price DECIMAL(14,2) DEFAULT 0, currency VARCHAR(10) DEFAULT 'TRY', disk_price DECIMAL(14,2) DEFAULT 0, traffic_price DECIMAL(14,2) DEFAULT 0, email_price DECIMAL(14,2) DEFAULT 0, requires_admin_approval TINYINT(1) DEFAULT 0, is_active TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"); }catch(Throwable $e){ error_log('[ao] '.$e->getMessage().' @ '.$e->getFile().':'.$e->getLine()); }
    try{ db()->exec("CREATE TABLE IF NOT EXISTS abandoned_carts (id INT AUTO_INCREMENT PRIMARY KEY, customer_id INT NULL, customer_name VARCHAR(190) NULL, email VARCHAR(190) NULL, phone VARCHAR(80) NULL, items_json LONGTEXT NULL, total DECIMAL(14,2) DEFAULT 0, currency VARCHAR(10) DEFAULT 'TRY', status VARCHAR(40) DEFAULT 'open', last_reminder_at DATETIME NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"); }catch(Throwable $e){ error_log('[ao] '.$e->getMessage().' @ '.$e->getFile().':'.$e->getLine()); }
    try{ db()->exec("CREATE TABLE IF NOT EXISTS automation_logs (id INT AUTO_INCREMENT PRIMARY KEY, rule_id INT NULL, status VARCHAR(40) DEFAULT 'success', message TEXT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"); }catch(Throwable $e){ error_log('[ao] '.$e->getMessage().' @ '.$e->getFile().':'.$e->getLine()); }
    try{ db()->exec("CREATE TABLE IF NOT EXISTS build_repository_files (id INT AUTO_INCREMENT PRIMARY KEY, project_name VARCHAR(190) NULL, file_type VARCHAR(20) DEFAULT 'apk', file_path VARCHAR(255) NULL, file_size BIGINT DEFAULT 0, status VARCHAR(40) DEFAULT 'ready', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"); }catch(Throwable $e){ error_log('[ao] '.$e->getMessage().' @ '.$e->getFile().':'.$e->getLine()); }
    try{ db()->exec("CREATE TABLE IF NOT EXISTS domain_document_rules (id INT AUTO_INCREMENT PRIMARY KEY, tld VARCHAR(40) NOT NULL, required_docs TEXT NULL, is_required TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uniq_tld(tld)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"); }catch(Throwable $e){ error_log('[ao] '.$e->getMessage().' @ '.$e->getFile().':'.$e->getLine()); }
    // notification compatibility
    try{ $cols=ao_v238_table_cols('notification_channels'); if($cols){ if(!empty($cols['channel'])) @db()->exec("ALTER TABLE notification_channels MODIFY channel VARCHAR(40) NULL"); if(empty($cols['channel_type']) && !empty($cols['channel'])) db()->exec("ALTER TABLE notification_channels ADD COLUMN channel_type VARCHAR(40) NULL AFTER id"); if(empty($cols['name'])) db()->exec("ALTER TABLE notification_channels ADD COLUMN name VARCHAR(190) NULL AFTER provider"); if(empty($cols['status'])) db()->exec("ALTER TABLE notification_channels ADD COLUMN status VARCHAR(40) DEFAULT 'inactive'"); if(empty($cols['test_mode'])) db()->exec("ALTER TABLE notification_channels ADD COLUMN test_mode TINYINT(1) DEFAULT 1"); if(empty($cols['priority'])) db()->exec("ALTER TABLE notification_channels ADD COLUMN priority INT DEFAULT 10"); if(empty($cols['sender_name'])) db()->exec("ALTER TABLE notification_channels ADD COLUMN sender_name VARCHAR(190) NULL"); db()->exec("UPDATE notification_channels SET channel_type=COALESCE(channel_type,channel), status=CASE WHEN is_active=1 THEN 'active' ELSE COALESCE(status,'inactive') END WHERE channel_type IS NULL OR channel_type='' OR status IS NULL"); }}catch(Throwable $e){ error_log('[ao] '.$e->getMessage().' @ '.$e->getFile().':'.$e->getLine()); }
    try{ $cols=ao_v238_table_cols('notification_logs'); if($cols){ if(!empty($cols['channel'])) @db()->exec("ALTER TABLE notification_logs MODIFY channel VARCHAR(40) NULL"); if(empty($cols['channel_type']) && !empty($cols['channel'])) db()->exec("ALTER TABLE notification_logs ADD COLUMN channel_type VARCHAR(40) NULL AFTER customer_id"); if(empty($cols['provider'])) db()->exec("ALTER TABLE notification_logs ADD COLUMN provider VARCHAR(120) NULL AFTER channel_type"); if(empty($cols['response_code'])) db()->exec("ALTER TABLE notification_logs ADD COLUMN response_code VARCHAR(20) NULL"); if(empty($cols['response_body'])) db()->exec("ALTER TABLE notification_logs ADD COLUMN response_body LONGTEXT NULL"); if(empty($cols['event_key'])) db()->exec("ALTER TABLE notification_logs ADD COLUMN event_key VARCHAR(120) NULL"); if(empty($cols['payload_json'])) db()->exec("ALTER TABLE notification_logs ADD COLUMN payload_json LONGTEXT NULL"); if(empty($cols['sent_at'])) db()->exec("ALTER TABLE notification_logs ADD COLUMN sent_at DATETIME NULL"); db()->exec("UPDATE notification_logs SET channel_type=COALESCE(channel_type,channel), response_body=COALESCE(response_body,provider_response) WHERE channel_type IS NULL OR response_body IS NULL"); }}catch(Throwable $e){ error_log('[ao] '.$e->getMessage().' @ '.$e->getFile().':'.$e->getLine()); }
    try{ $cols=ao_v238_table_cols('notification_templates'); if($cols && empty($cols['event_key']) && !empty($cols['template_key'])) db()->exec("ALTER TABLE notification_templates ADD COLUMN event_key VARCHAR(120) NULL AFTER id"); }catch(Throwable $e){ error_log('[ao] '.$e->getMessage().' @ '.$e->getFile().':'.$e->getLine()); }
}
ao_v238_ensure_schema();
function ao_v238_slug($s){ $s=trim($s); $s=preg_replace('/[^a-z0-9]+/','-',strtolower(iconv('UTF-8','ASCII//TRANSLIT//IGNORE',$s) ?: $s)); return trim($s,'-') ?: 'item'; }

if ($_SERVER['REQUEST_METHOD']==='POST' && $route==='admin/product-center/custom-field-save') { require_admin(); verify_csrf(); ao_v238_ensure_schema(); $label=trim($_POST['label']??''); $key=trim($_POST['field_key']??'') ?: ao_v238_slug($label); if($label===''){ flash('error','Alan adı zorunlu.'); redirect_to('admin/product-center/custom-fields'); } try{ db()->prepare('INSERT INTO product_custom_fields(group_id,product_id,field_key,label,field_type,options,is_required,is_active,sort_order) VALUES(?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE label=VALUES(label),field_type=VALUES(field_type),options=VALUES(options),is_required=VALUES(is_required),is_active=VALUES(is_active),sort_order=VALUES(sort_order)')->execute([(int)($_POST['group_id']??0),(int)($_POST['product_id']??0),$key,$label,$_POST['field_type']??'text',$_POST['options']??'',isset($_POST['is_required'])?1:0,isset($_POST['is_active'])?1:0,(int)($_POST['sort_order']??0)]); flash('success','Özel alan kaydedildi.'); }catch(Throwable $e){ flash('error','Özel alan kaydedilemedi: '.$e->getMessage()); } redirect_to('admin/product-center/custom-fields'); }
if ($route==='admin/product-center/custom-field-toggle'){ require_admin(); verify_csrf(); ao_v238_ensure_schema(); $id=(int)($_GET['id']??0); try{$cur=(int)db()->query('SELECT is_active FROM product_custom_fields WHERE id='.$id)->fetchColumn(); db()->prepare('UPDATE product_custom_fields SET is_active=? WHERE id=?')->execute([$cur?0:1,$id]); flash('success','Özel alan durumu değiştirildi.');}catch(Throwable $e){flash('error','İşlem başarısız.');} redirect_to('admin/product-center/custom-fields'); }
if ($route==='admin/product-center/custom-field-delete'){ require_admin(); verify_csrf(); ao_v238_ensure_schema(); $id=(int)($_GET['id']??0); try{db()->prepare('DELETE FROM product_custom_fields WHERE id=?')->execute([$id]); flash('success','Özel alan silindi.');}catch(Throwable $e){flash('error','Silinemedi.');} redirect_to('admin/product-center/custom-fields'); }

if ($_SERVER['REQUEST_METHOD']==='POST' && $route==='admin/product-center/promotion-save') { require_admin(); verify_csrf(); ao_v238_ensure_schema(); $code=strtoupper(trim($_POST['code']??'')); if($code===''){ flash('error','Kupon kodu zorunlu.'); redirect_to('admin/product-center/promotions'); } try{ db()->prepare('INSERT INTO product_promotions(code,title,discount_type,discount_value,min_total,usage_limit,starts_at,ends_at,is_active) VALUES(?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE title=VALUES(title),discount_type=VALUES(discount_type),discount_value=VALUES(discount_value),min_total=VALUES(min_total),usage_limit=VALUES(usage_limit),starts_at=VALUES(starts_at),ends_at=VALUES(ends_at),is_active=VALUES(is_active)')->execute([$code,trim($_POST['title']??''),$_POST['discount_type']??'percent',(float)($_POST['discount_value']??0),(float)($_POST['min_total']??0),(int)($_POST['usage_limit']??0),($_POST['starts_at']??'')?:null,($_POST['ends_at']??'')?:null,isset($_POST['is_active'])?1:0]); flash('success','Promosyon kaydedildi.'); }catch(Throwable $e){ flash('error','Promosyon kaydedilemedi: '.$e->getMessage()); } redirect_to('admin/product-center/promotions'); }
if ($route==='admin/product-center/promotion-toggle'){ require_admin(); verify_csrf(); ao_v238_ensure_schema(); $id=(int)($_GET['id']??0); try{$cur=(int)db()->query('SELECT is_active FROM product_promotions WHERE id='.$id)->fetchColumn(); db()->prepare('UPDATE product_promotions SET is_active=? WHERE id=?')->execute([$cur?0:1,$id]); flash('success','Promosyon durumu değiştirildi.');}catch(Throwable $e){flash('error','İşlem başarısız.');} redirect_to('admin/product-center/promotions'); }
if ($route==='admin/product-center/promotion-delete'){ require_admin(); verify_csrf(); ao_v238_ensure_schema(); $id=(int)($_GET['id']??0); try{db()->prepare('DELETE FROM product_promotions WHERE id=?')->execute([$id]); flash('success','Promosyon silindi.');}catch(Throwable $e){flash('error','Silinemedi.');} redirect_to('admin/product-center/promotions'); }

if ($_SERVER['REQUEST_METHOD']==='POST' && $route==='admin/product-center/bundle-save') { require_admin(); verify_csrf(); ao_v238_ensure_schema(); $name=trim($_POST['name']??''); if($name===''){ flash('error','Paket adı zorunlu.'); redirect_to('admin/product-center/bundles'); } try{ db()->prepare('INSERT INTO package_builders(name,base_price,currency,disk_price,traffic_price,email_price,requires_admin_approval,is_active) VALUES(?,?,?,?,?,?,?,?)')->execute([$name,(float)($_POST['base_price']??0),$_POST['currency']??'TRY',(float)($_POST['disk_price']??0),(float)($_POST['traffic_price']??0),(float)($_POST['email_price']??0),isset($_POST['requires_admin_approval'])?1:0,isset($_POST['is_active'])?1:0]); flash('success','Paket kuralı kaydedildi.'); }catch(Throwable $e){ flash('error','Paket kuralı kaydedilemedi: '.$e->getMessage()); } redirect_to('admin/product-center/bundles'); }
if ($route==='admin/product-center/bundle-toggle'){ require_admin(); verify_csrf(); ao_v238_ensure_schema(); $id=(int)($_GET['id']??0); try{$cur=(int)db()->query('SELECT is_active FROM package_builders WHERE id='.$id)->fetchColumn(); db()->prepare('UPDATE package_builders SET is_active=? WHERE id=?')->execute([$cur?0:1,$id]); flash('success','Paket durumu değiştirildi.');}catch(Throwable $e){flash('error','İşlem başarısız.');} redirect_to('admin/product-center/bundles'); }
if ($route==='admin/product-center/bundle-delete'){ require_admin(); verify_csrf(); ao_v238_ensure_schema(); $id=(int)($_GET['id']??0); try{db()->prepare('DELETE FROM package_builders WHERE id=?')->execute([$id]); flash('success','Paket kuralı silindi.');}catch(Throwable $e){flash('error','Silinemedi.');} redirect_to('admin/product-center/bundles'); }

if ($route==='admin/orders/abandoned-remind'){ require_admin(); verify_csrf(); ao_v238_ensure_schema(); $id=(int)($_GET['id']??0); try{db()->prepare('UPDATE abandoned_carts SET last_reminder_at=NOW() WHERE id=?')->execute([$id]); flash('success','Hatırlatma kuyruğa alındı.');}catch(Throwable $e){flash('error','Hatırlatma gönderilemedi.');} redirect_to('admin/orders/abandoned'); }
if ($route==='admin/orders/abandoned-close'){ require_admin(); verify_csrf(); ao_v238_ensure_schema(); $id=(int)($_GET['id']??0); try{db()->prepare("UPDATE abandoned_carts SET status='closed' WHERE id=?")->execute([$id]); flash('success','Sepet kapatıldı.');}catch(Throwable $e){flash('error','İşlem başarısız.');} redirect_to('admin/orders/abandoned'); }

if ($_SERVER['REQUEST_METHOD']==='POST' && $route==='admin/automation/save'){ require_admin(); verify_csrf(); ao_v238_ensure_schema(); $name=trim($_POST['name']??''); if($name===''){flash('error','Kural adı zorunlu.'); redirect_to('admin/automation');} try{ db()->prepare('INSERT INTO automation_rules(name,trigger_event,action_type,is_active,config_json) VALUES(?,?,?,?,?)')->execute([$name,$_POST['trigger_event']??'',$_POST['action_type']??'',isset($_POST['is_active'])?1:0,json_encode(['condition'=>$_POST['condition_json']??'','action'=>$_POST['action_json']??''],JSON_UNESCAPED_UNICODE)]); flash('success','Otomasyon kuralı kaydedildi.'); }catch(Throwable $e){ flash('error','Kural kaydedilemedi: '.$e->getMessage()); } redirect_to('admin/automation'); }
if ($route==='admin/automation/toggle'){ require_admin(); verify_csrf(); ao_v238_ensure_schema(); $id=(int)($_GET['id']??0); try{$cur=(int)db()->query('SELECT is_active FROM automation_rules WHERE id='.$id)->fetchColumn(); db()->prepare('UPDATE automation_rules SET is_active=? WHERE id=?')->execute([$cur?0:1,$id]); flash('success','Kural durumu değiştirildi.');}catch(Throwable $e){flash('error','İşlem başarısız.');} redirect_to('admin/automation'); }
if ($route==='admin/automation/delete'){ require_admin(); verify_csrf(); $id=(int)($_GET['id']??0); try{db()->prepare('DELETE FROM automation_rules WHERE id=?')->execute([$id]); flash('success','Kural silindi.');}catch(Throwable $e){flash('error','Silinemedi.');} redirect_to('admin/automation'); }

if ($route==='admin/backup-center/delete'){ require_admin(); verify_csrf(); $id=(int)($_GET['id']??0); try{$q=db()->prepare('SELECT file_path FROM backup_jobs WHERE id=?');$q->execute([$id]);$fp=$q->fetchColumn(); if($fp && is_file($fp)) @unlink($fp); db()->prepare('DELETE FROM backup_jobs WHERE id=?')->execute([$id]); flash('success','Yedek silindi.');}catch(Throwable $e){flash('error','Yedek silinemedi.');} redirect_to('admin/backup-center'); }
if ($route==='admin/backup-center/cleanup'){ require_admin(); verify_csrf(); $days=(int)($_GET['days']??30); try{db()->prepare('DELETE FROM backup_jobs WHERE created_at < DATE_SUB(NOW(), INTERVAL ? DAY)')->execute([$days]); flash('success',$days.' günden eski yedek kayıtları temizlendi.');}catch(Throwable $e){flash('error','Temizlik yapılamadı.');} redirect_to('admin/backup-center'); }
if ($_SERVER['REQUEST_METHOD']==='POST' && $route==='admin/backup-center/test-target'){ require_admin(); verify_csrf(); flash('success','Yedek hedefi test edildi. Gerçek uzak bağlantı bilgileri kaydedildiğinde canlı test yapılır.'); redirect_to('admin/backup-center'); }

if ($route==='admin/update-center/delete'){ require_admin(); verify_csrf(); $file=basename($_GET['file']??''); $p=__DIR__.'/database/migrations/'.$file; if($file && is_file($p)){@unlink($p); flash('success','Migration silindi.');} else flash('error','Dosya bulunamadı.'); redirect_to('admin/update-center'); }
if ($route==='admin/update-center/archive' || $route==='admin/update-center/archive-old'){ require_admin(); verify_csrf(); $dir=__DIR__.'/database/migrations'; $arc=$dir.'/archive'; if(!is_dir($arc)) @mkdir($arc,0775,true); if($route==='admin/update-center/archive'){ $file=basename($_GET['file']??''); if($file && is_file($dir.'/'.$file)) @rename($dir.'/'.$file,$arc.'/'.$file); } else { foreach(glob($dir.'/v*.sql') as $p){ if(!str_contains(basename($p),'22_3')) @rename($p,$arc.'/'.basename($p)); } } flash('success','Migration arşivleme tamamlandı.'); redirect_to('admin/update-center'); }


if ($_SERVER['REQUEST_METHOD']==='POST' && $route==='admin/build-center/repository-delete'){ require_admin(); verify_csrf(); ao_v238_ensure_schema(); $ids=array_map('intval', $_POST['ids']??[]); $n=0; foreach($ids as $id){ try{$q=db()->prepare('SELECT file_path FROM build_repository_files WHERE id=?');$q->execute([$id]);$fp=$q->fetchColumn(); if($fp && is_file($fp)) @unlink($fp); db()->prepare('DELETE FROM build_repository_files WHERE id=?')->execute([$id]); $n++;}catch(Throwable $e){ error_log('[ao] '.$e->getMessage().' @ '.$e->getFile().':'.$e->getLine()); } } flash('success',$n.' dosya kaydı temizlendi.'); redirect_to('admin/build-center/repository'); }
if ($route==='admin/build-center/repository-clean'){ require_admin(); verify_csrf(); ao_v238_ensure_schema(); $days=(int)($_GET['days']??30); try{db()->prepare('DELETE FROM build_repository_files WHERE created_at < DATE_SUB(NOW(), INTERVAL ? DAY)')->execute([$days]); flash('success','Eski build çıktıları temizlendi.');}catch(Throwable $e){flash('error','Temizlik yapılamadı.');} redirect_to('admin/build-center/repository'); }

if ($route === 'admin/cache-center/clear' && $_SERVER['REQUEST_METHOD'] === 'POST') {
    require_admin(); verify_csrf(); $area=$_POST['area'] ?? 'all'; $n=ao_v980_cache_clear($area); flash('success', $n.' cache dosyası temizlendi.'); redirect_to('admin/cache-center');
}
if ($route === 'admin/backup-center/create' && $_SERVER['REQUEST_METHOD'] === 'POST') {
    require_admin(); verify_csrf(); $type=$_POST['backup_type'] ?? 'database'; $file=ao_v1000_backup_create($type); flash('success', 'Yedek oluşturuldu: '.basename($file)); redirect_to('admin/backup-center');
}
if ($route === 'admin/backup-center/download') {
    require_admin(); $id=(int)($_GET['id'] ?? 0); $s=db()->prepare('SELECT * FROM backup_jobs WHERE id=? LIMIT 1'); $s->execute([$id]); $b=$s->fetch(); if(!$b || empty($b['file_path']) || !is_file($b['file_path'])) { http_response_code(404); echo 'Yedek bulunamadı'; exit; } header('Content-Type: application/octet-stream'); header('Content-Disposition: attachment; filename="'.basename($b['file_path']).'"'); readfile($b['file_path']); exit;
}
if ($route === 'admin/update-center/run' && $_SERVER['REQUEST_METHOD'] === 'POST') {
    require_admin(); verify_csrf(); $res=ao_v1000_run_migration($_POST['migration_file'] ?? ''); flash($res['ok']?'success':'error', $res['message']); redirect_to('admin/update-center');
}
if ($route === 'admin/database-upgrade/apply' && $_SERVER['REQUEST_METHOD'] === 'POST') {
    require_admin(); verify_csrf(); $res=ao_database_upgrade_check(true);
    $level = !empty($res['errors']) ? 'error' : 'success';
    flash($level, (int)$res['applied'].' guvenli veritabani duzeltmesi uygulandi'.(!empty($res['errors']) ? '; '.(int)$res['errors'].' islem hata verdi.' : '.'));
    redirect_to('admin/database-upgrade');
}

if ($route === 'admin/production-test') {
    require_admin();
    view('production-test/index', ['pageTitle'=>'Production Test & Cleanup', 'items'=>ao_v960_production_summary()]);
    exit;
}

if ($route === 'admin/search') {
    require_admin();
    view('search/index', ['pageTitle'=>'Admin Arama', 'query'=>trim($_GET['q'] ?? ''), 'results'=>ao_admin_search_results($_GET['q'] ?? '')]);
    exit;
}


if ($route === 'admin/cache-center') { require_admin(); view('cache-center/index', ['pageTitle'=>'Cache Temizleme Merkezi', 'events'=>ao_v980_cache_rows()]); exit; }
if ($route === 'admin/backup-center') { require_admin(); view('backup-center/index', ['pageTitle'=>'Backup Center', 'backups'=>ao_v980_backup_rows()]); exit; }
if ($route === 'admin/security') { require_admin(); view('security/index', array_merge(['pageTitle'=>'Güvenlik & Yetkiler'], ao_v980_security_items())); exit; }
if ($route === 'admin/update-center') { require_admin(); view('update-center/index', ['pageTitle'=>'Update Center', 'migrations'=>ao_v1000_migrations()]); exit; }
if ($route === 'admin/database-upgrade') { require_admin(); view('database-upgrade/index', ['pageTitle'=>'Database Upgrade Wizard', 'upgrade'=>ao_database_upgrade_check(false)]); exit; }
if ($route === 'admin/notification-center') { require_admin(); view('notification-center/index', ['pageTitle'=>'Notification Center', 'summary'=>ao_v1000_notification_summary()]); exit; }
